services:
  - type: web
    name: expense-tracker-api
    runtime: node
    region: singapore  # Choose closest to your users: oregon|frankfurt|singapore
    branch: main       # Your git branch to deploy
    autoDeploy: true   # Enable automatic deploys on git push
    
    # Build configuration
    buildCommand: |
      npm install
      npm run migrate:up  # Run database migrations
      
    startCommand: npm start
    
    # Health check path (important for zero-downtime deploys)
    healthCheckPath: /
    healthCheckTimeout: 30s
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
        
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
          
      - key: JWT_SECRET
        generateValue: true  # Render will auto-generate a secure secret
        
      - key: PORT
        value: 10000  # Must match your server.js port
        
    # Advanced scaling (free tier limits)
    plan: free  # free|starter|standard
    numInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

databases:
  - name: expense-tracker-db
    databaseName: neondb
    user: neondb_owner
    plan: free  # free|starter|standard
    region: us-east-1  # Match Neon's region